language: c++
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
before_script:
  - if test CC=gcc && which gcc-6 >/dev/null 2>&1; then export CC=gcc-6 CXX=g++-6; fi
  - if test CC=gcc && which gcc-5 >/dev/null 2>&1; then export CC=gcc-5 CXX=g++-5; fi
  - ./bootstrap.sh
script: ./configure && make
sudo: false
