#! /bin/sh
#
# chkconfig: - 86 13
# description: HotCRP Comet manager
# processname: hotcrp-comet
# pidfile: /var/run/hotcrp-comet/hotcrp-comet.pid

# Source function library.
. /etc/init.d/functions

# Check that networking is up.
. /etc/sysconfig/network

# Additional environment file
if [ -f /etc/sysconfig/hotcrp-comet ]; then
    . /etc/sysconfig/hotcrp-comet
fi

if [ "$NETWORKING" = "no" ]; then
    exit 0
fi

RETVAL=0
prog="hotcrp-comet"
pidfile=${PIDFILE-/var/run/hotcrp-comet/hotcrp-comet.pid}
logfile=${LOGFILE-/var/log/hotcrp-comet.log}
lockfile=${LOCKFILE-/var/lock/subsys/hotcrp-comet}
comet_args=${HOTCRP_COMET_ARGS---log-file $logfile}

start () {
        echo -n $"Starting $prog: "
        dir=$(dirname ${pidfile})
        [ -d $dir ] || mkdir $dir
        daemon --pidfile ${pidfile} hotcrp-comet $comet_args
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch ${lockfile}
}
stop () {
        echo -n $"Stopping $prog: "
        killproc -p ${pidfile} hotcrp-comet
        RETVAL=$?
        echo
        if [ $RETVAL -eq 0 ] ; then
                rm -f ${lockfile} ${pidfile}
        fi
}

restart () {
        stop
        start
}


# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status -p ${pidfile} hotcrp-comet
        RETVAL=$?
        ;;
  restart)
        restart
        ;;
  condrestart|try-restart)
        [ -f ${lockfile} ] && restart || :
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        RETVAL=2
        ;;
esac

exit $RETVAL
